apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: kanban-api
  labels: {{ toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: kanban-api
  template:
    metadata:
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: kanban-api
    spec:
      containers:
        - name: kanban-api
          image: {{.Values.image.apiname}}
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: {{.Values.http.backendport}}
          env:
            - name: CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: secrets-kanban
                  key: CONNECTION_URL
      restartPolicy: Always