apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: kanban-frontend
  labels:
    app: kanban-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-frontend
  template:
    metadata:
      labels:
        app: kanban-frontend
    spec:
      containers:
        - name: kanban-frontend
          image: yasminecherif/kanban-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          