apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: kanban-api
  labels:
    app: kanban-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-api
  template:
    metadata:
      labels:
        app: kanban-api
    spec:
      containers:
        - name: kanban-api
          image: yasminecherif/kanban-api
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: 5000
          env:
            - name: CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: secrets-kanban
                  key: CONNECTION_URL
      restartPolicy: Always